feat: integration test
pagopa/pagopa-gpd-reporting-batch pull request #5
Opened 2023-04-28 16:43 UTC by AngeloCaporaso

#### List of Changes

- integration test migration and validation from `https://github.com/pagopa/pagopa-debt-position`

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-05-08 07:55 UTC, jacopocarlini requested changes
can you use the [new](https://github.com/pagopa/pagopa-gpd-payments/pull/41/files) approach for integration tests?

2023-08-21 09:03 UTC, FedericoRuzzier commented on integration-test/src/config/.env.local
> +reporting_analysis_host=https://localhost:8080/gpd-reporting/api/v1 # TODO to be changed, only a placeholder
Remove TODOs

2023-08-21 09:07 UTC, FedericoRuzzier commented on integration-test/README.MD
> +```
There is only one key in the implementation, update README

2023-08-21 09:11 UTC, FedericoRuzzier approved these changes
LGTM 👍 , take a look at comments before merging

2023-08-21 09:30 UTC, merged